name: test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend: [pysail, pyspark]
    name: test (${{ matrix.backend }})
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix develop --command pytest -v
        env:
          SPARK_BACKEND: ${{ matrix.backend }}
